IN_USE = ["Argentina",
          "Austria-Hungary",
          "Bahrain",
          "Belgium",
          "Brazil",
          "Canada",
          "Chile",
          "China",
          "Colombia",
          "Confederates States of America",
          "Cuba",
          "Dominican Republic",
          "Ecuador",
          "Egypt",
          "Ethiopia",
          "Fiji",
          "France",
          "Germany",
          "Greece",
          "Haiti",
          "India",
          "Indonesia",
          "Iran",
          "Italy",
          "Japan",
          "Liberia",
          "Malaysia",
          "Marshall Islands",
          "Mexico",
          "Monaco",
          "Morocco",
          "Myanmar",
          "Netherlands",
          "New Zealand",
          "Newfoundland",
          "Norway",
          "Pakistan",
          "Palau",
          "Panama",
          "Peru",
          "Philippines",
          "Poland",
          "Portugal",
          "Puerto Rico",
          "Saudi Arabia",
          "Singapore",
          "South Africa",
          "South Korea",
          "South Vietnam",
          "Soviet Union",
          "Spain",
          "Sweden",
          "Taiwan",
          "Thailand",
          "Trust Territory of the Pacific Islands",
          "Tunisia",
          "Turkey",
          "United Kingdom",
          "United States",
          "Uruguay",
          "Venezuela",
          "Vietnam",
          "West Germany"]

DROP = ["Ships grouped alphabetically", ]

REPL = {"America": "United States",
        "Commonwealth of the Philippines": "Philippines",
        "Confederate States": "Confederates States of America",
        "Confederate States Navy": "Confederates States of America",
        "Empire of Japan": "Japan",
        "Ethiopian": "Ethiopia",
        "Free France": "France",
        "German Empire": "Germany",
        "Great Britain": "United Kingdom",
        "Guam": "United States",
        "Nazi Germany": "Germany",
        "People's Republic of China": "China",
        "Philippine": "Philippines",
        "Republic of China": "Taiwan",
        "Republic of Fiji": "Fiji",
        "Republic of France": "France",
        "Republic of Palau": "Palau",
        "Republic of Peru": "Peru",
        "Republic of Vietnam Navy": "South Vietnam",
        "Republic of the Marshall Islands": "Marshall Islands",
        "Royal NavyUnited Kingdom": "United Kingdom",
        "Second French Empire": "France",
        "U.S.": "United States",
        "U.S. Bureau of Fisheries": "United States",
        "U.S. Coast and Geodetic Survey": "United States",
        "U.S. Fish and Wildlife Service": "United States",
        "U.S. Navy": "United States",
        "Union of South Africa": "South Africa",
        "United States Army": "United States",
        "United States Coast Guard": "United States",
        "United States Geological Survey": "United States",
        "United States Lighthouse Service": "United States",
        "United States Lines": "United States",
        "United States Navy": "United States",
        "United States NavyUnited States": "United States",
        "United States Philippines": "United States",
        "United States Revenue Cutter Service": "United States",
        "United StatesUnited States": "United States",
        "Vietnam People's Navy": "Vietnam"
        }
